<!DOCTYPE html>
<html>
<head>
    <title>DvSoftware :: demo REST API - work with users</title>
</head>
<body>
<style>
    table.rest {
        border: 1px solid #000;
        border-spacing: 0;
        border-collapse: collapse;
        margin-bottom: 10px;
    }

    table.rest td {
        border: 1px solid #000;
        padding: 5px;
    }

    table.rest td.method {
        background-color: darkgray;
    }
</style>
<h1>Demo REST API </h1>
<table class="rest" border="">
    <tr>
        <td colspan="3" class="method">GET</td>
    </tr>
    <tr>
        <td>/user</td>
        <td>Get all users</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>/user/[id]</td>
        <td>get user by primary key (id)</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>/user/search/[email]</td>
        <td>find users by email</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td colspan="3" class="method">
            POST
        </td>
    </tr>
    <tr>
        <td>/user</td>
        <td>create a new user</td>
        <td>{"name":"user","email":"user@website.com"}</td>
    </tr>
    <tr>
        <td colspan="3" class="method">
            PUT
        </td>
    </tr>
    <tr>
        <td>/user/[id]</td>
        <td>update user by primary key (id)</td>
        <td>{"name":"user0","email":"user0@website.com"}</td>
    </tr>
    <tr>
        <td colspan="3" class="method">
            DELETE
        </td>
    </tr>
    <tr>
        <td>/user/[id]</td>
        <td>delete user by primary key (id)</td>
        <td>&nbsp</td>
    </tr>
</table>
&copy; DvSoftware
</body>
</html>